name = "pohlang-playground"
compatibility_date = "2024-01-01"
pages_build_output_dir = "web"

[vars]
# Set RUNNER_ORIGIN in Cloudflare Pages dashboard
# Example: RUNNER_ORIGIN = "https://your-runner.example.com"
