name: Deploy to Cloudflare Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'web/**'
      - '.github/workflows/cloudflare-pages.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Only run if Cloudflare secrets are configured
    if: ${{ secrets.CF_API_TOKEN != '' && secrets.CF_ACCOUNT_ID != '' }}
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: pohlang-playground
          directory: ./web
          wranglerVersion: '3'
